[build]
builder = "NIXPACKS"
nixpacksPlan = { phases = { install = { dependsOn = ["setup"], cmds = ["curl -LsSf https://astral.sh/uv/install.sh | sh", "uv sync"] } } }

[deploy]
startCommand = "uv run fastmcp-server"
restartPolicyType = "on_failure"
healthcheckPath = "/mcp/"
healthcheckTimeout = 60

[env]
ELASTICSEARCH_URL = "http://${{elasticsearch.RAILWAY_PRIVATE_DOMAIN}}:9200"
