[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.elasticsearch"

[deploy]
restartPolicyType = "on_failure"

[env]
discovery.type = "single-node"
xpack.security.enabled = "false"
ES_JAVA_OPTS = "-Xms1g -Xmx2g"
cluster.name = "railway-elasticsearch"
network.host = "0.0.0.0"
http.port = "9200"
bootstrap.memory_lock = "false"

